"""add password login columns to patients and resources

Revision ID: 8e2bd623bc0e
Revises: 6578d1fee0c9
Create Date: 2026-07-19 00:05:11.807104

FR-18 password login: `patients.password_hash` (patient login, username = patient_code) and
`resources.username`/`resources.password_hash` (doctor login, for now - see
`auth/password_login.py`). Hand-trimmed from the autogenerated diff: the live DB has drifted from
`state/sql/models.py` on unrelated nullability/indexes (pre-existing, not this change's concern) -
only the three new columns and the one unique constraint below belong to this migration.
"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '8e2bd623bc0e'
down_revision: str | Sequence[str] | None = '6578d1fee0c9'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.add_column('patients', sa.Column('password_hash', sa.Text(), nullable=True))
    op.add_column('resources', sa.Column('username', sa.Text(), nullable=True))
    op.add_column('resources', sa.Column('password_hash', sa.Text(), nullable=True))
    op.create_unique_constraint('uq_resources_username', 'resources', ['username'])


def downgrade() -> None:
    op.drop_constraint('uq_resources_username', 'resources', type_='unique')
    op.drop_column('resources', 'password_hash')
    op.drop_column('resources', 'username')
    op.drop_column('patients', 'password_hash')
