"""Domain models for VAIC (entities, enums, state machines)."""

from __future__ import annotations

from .entities import (
    ENTITIES,
    Appointment,
    AuditLogEntry,
    CarePlan,
    Department,
    Diagnosis,
    DisruptionEvent,
    IntakeSession,
    Notification,
    Patient,
    Payment,
    QueueTicket,
    Resource,
    ScanEvent,
    ServiceOrder,
    ServiceType,
    Slot,
    Task,
)
from .enums import (
    AppointmentStatus,
    CarePlanStatus,
    DisruptionEventType,
    DisruptionStatus,
    ExecutionStatus,
    NotificationChannel,
    PaymentStatus,
    PaymentSubjectType,
    PriorityLevel,
    QueueSubjectType,
    QueueTicketStatus,
    ResourceType,
)
from .transitions import (
    APPOINTMENT_TRANSITIONS,
    CAREPLAN_TRANSITIONS,
    DISRUPTION_TRANSITIONS,
    QUEUE_TICKET_TRANSITIONS,
    TASK_TRANSITIONS,
    InvalidTransition,
    assert_transition,
    can_transition,
)

__all__ = [
    "ENTITIES",
    "Appointment",
    "AuditLogEntry",
    "CarePlan",
    "Department",
    "Diagnosis",
    "DisruptionEvent",
    "IntakeSession",
    "Notification",
    "Patient",
    "Payment",
    "QueueTicket",
    "Resource",
    "ScanEvent",
    "ServiceOrder",
    "ServiceType",
    "Slot",
    "Task",
    "AppointmentStatus",
    "CarePlanStatus",
    "DisruptionEventType",
    "DisruptionStatus",
    "ExecutionStatus",
    "NotificationChannel",
    "PaymentStatus",
    "PaymentSubjectType",
    "PriorityLevel",
    "QueueSubjectType",
    "QueueTicketStatus",
    "ResourceType",
    "APPOINTMENT_TRANSITIONS",
    "CAREPLAN_TRANSITIONS",
    "DISRUPTION_TRANSITIONS",
    "QUEUE_TICKET_TRANSITIONS",
    "TASK_TRANSITIONS",
    "InvalidTransition",
    "assert_transition",
    "can_transition",
]
